fix (mypy-plugin): tuple object does not support item assignment
fix #62: 
/pfun/mypy_plugin.py", line 396, in _combine_hook
    ret_type_args[1] = combined_error_type
TypeError: 'tuple' object does not support item assignment